### ISSUE TITLE
Raw Data Cleaning

### ISSUE THREAD

**Issue by rodrigofegui** [rodrigofegui/IA-proj3#1]
## Description
The raw dataset was gathered by the _Hospital Israelita Albert Einstein_, São Paulo (Brazil), with real data related to COVID-19 treated patients. Because of that, there are humanized values, such as: "undetected", "detected" or "Não realizado", that are hard to a computer direct interpretation, asking for a raw filter as simple as "undetected" equals to 0, for instance, or some value easily measurable the computers.

## Acception criteria
- [x] Detect the majority or all humanized values
- [x] Replace those values
    - Blank space is different from 0
- [x] Duplicate `dtype=object` columns as `dtype=number` columns

**Comment by gust-luiz** [comment]
Tasks solved in commit dc922d2fe78aa549e20835191253b35692fcfb22

**Comment by gust-luiz** [comment]
Possibilities for filling NaN solved in commit 800c541f2e0f2805684103f9d7f3c9308e60b03a
